### ISSUE TITLE
Admin 

### ISSUE THREAD

**Issue by LCMiller** [pichalite/nodebb-plugin-newuser-approval#1]
Hi, having some problems with the plugin, there are eight unapproved members but I am unable to see them in the plugin admin page?

![admin-approval2](https://cloud.githubusercontent.com/assets/6793181/6992411/993439a0-dac4-11e4-8fa9-b983b8a23a1f.jpg)

![admin-approval1](https://cloud.githubusercontent.com/assets/6793181/6992410/9472c382-dac4-11e4-8f7e-006d79912afd.jpg)

cheers, Lee

**Comment by pichalite** [comment]
@LCMiller your group is named "non-approved" but you entered "Non approved" in the plugin settings. Fix that and it should work.

**Comment by LCMiller** [comment]
hi @pichalite :smile: that solved it perfectly, many thanks.
