### ISSUE TITLE
Save settings doesn't work [0.0.2] [NodeBB v0.7.0 dev]

### ISSUE THREAD

**Issue by 68040** [pichalite/nodebb-plugin-newuser-approval#2]
1. Go to ACP > Installed PlugIns > New User Approval.
2. Enter group name of an "Non approved users group".
3. Click "Save Setting".
4. Go to ACP > General > Dashboard. And return to ACP > Installed PlugIns > New User Approval.

Result: The settings field for non approved users group is empty.

**Comment by pichalite** [comment]
The plugin is not compatible with NodeBB v0.7.0-dev. Will be updated after NodeBB v0.7.0 is released.
