### ISSUE TITLE
PlugIn doesn't work [0.0.2] [NodeBB v0.7.0 dev]

### ISSUE THREAD

**Issue by 68040** [pichalite/nodebb-plugin-newuser-approval#3]
1. Log in as admin. Install and activate the plugin.
2. Open a another browser and register a new user.
3. Switch back to the Browser with the Admin Panel.
4. Got to ACP > Installed PlugIns > New User Approval. -> There is no new user!
5. Go to ACP > Manage > Groups. -> In the non approved users group is no new User.

**Comment by pichalite** [comment]
Did you set the "non approved" and "approved" user groups in plugin settings page and restart your NodeBB after activating the plugin?

The plugin is not compatible with NodeBB v0.7.0-dev

**Comment by 68040** [comment]
> Did you set the "non approved" and "approved" user groups in plugin settings page and restart your NodeBB after activating the plugin?

Yes. I restarted NodeBB and set it to "_want-to-be-free_" and to "_registered-users_".

> The plugin is not compatible with NodeBB v0.7.0-dev

Now i know.

**Comment by NoodleBB** [comment]
Interesting, they appear in that group ()
