### ISSUE TITLE
New Users are not added into "New User Approval" Section

### ISSUE THREAD

**Issue by Scott-S** [pichalite/nodebb-plugin-newuser-approval#5]
Hello!

- Does this plugin work with NodeBB v1.5.1? When I create new users I don't see them show up in the Plugin > "New User Approval" section
- I do notice that they get added to the correct group, just not in the "New User Approval" section
- See logging attached as well

<img width="659" alt="screen shot 2017-06-22 at 11 51 37 pm" src="https://user-images.githubusercontent.com/10150566/27469929-84ed441c-57a6-11e7-8589-cccc354d95c0.png">
<img width="877" alt="screen shot 2017-06-22 at 11 51 09 pm" src="https://user-images.githubusercontent.com/10150566/27469930-84f091c6-57a6-11e7-8fbd-c3ca7b15c44a.png">
<img width="1125" alt="screen shot 2017-06-22 at 11 50 52 pm" src="https://user-images.githubusercontent.com/10150566/27469934-850d0dd8-57a6-11e7-9ce3-5f548fbb77fe.png">
<img width="920" alt="screen shot 2017-06-22 at 11 50 41 pm" src="https://user-images.githubusercontent.com/10150566/27469931-84fd2774-57a6-11e7-9727-2ac184a91aab.png">

**Comment by dnkls** [comment]
the same situation

**Comment by pichalite** [comment]
Get latest version.
